### PR TITLE
Pencil Thickness Slider 

### PR DESCRIPTION
**Pull request by arzitmahajan**
Pencil thickness could be changed using the slider

### CODE REVIEW

**Comment by arzitmahajan** [comment]
#26 Please review the PR and mark appropriate labels

**Comment by vedant-jain03** [comment]
Why you delete lock file?

**Comment by arzitmahajan** [comment]
This error was persisting in previous PR also can you tell me how to recover the lock file I tried npm install also but it didn't worked

**Comment by vedant-jain03** [comment]
I guess you are not commiting the files in the correct directory.
In most of the cases this is only the problem or say small mistake.

**Comment by arzitmahajan** [comment]
I created a branch then made changes in code and then pushed it after committing using [ git push -u origin "branch name" ]

**Comment by arzitmahajan** [comment]
Please check now

**Comment by arzitmahajan** [comment]
I directly pasted the lock files

**Review by vedant-jain03 — APPROVED** [review]

**Comment by vedant-jain03** [comment]
@arzitmahajan Good work
When you format the file it means you have added something(space) and as result it get add in number of lines. Your solution required 50 LOC but it is giving 400+ this is the reason for it.
Please be sure from next time, I hope you got something new.

**Comment by arzitmahajan** [comment]
Yes I noticed I don't why that happened its first time I am facing this kind of issue even there were spaces in lock file it was deleted . I will try my best that this thing don't happen again thanks a lot for approving this PR.

**Pull request merged**
