### PR TITLE
Export Images as PNG Functionality

### LINKED ISSUE #46: Add an export button functionality
an export button functionality where users can export their drawing / creatives into image format

### PR DESCRIPTION
**Pull request by Shubham29012001**
Fix #46, I have developed the export image functionality. Please assign the GSSoC'22 and Level label on the issue so that it would contribute to my efforts.

### CODE REVIEW

**Comment by Shubham29012001** [comment]
Hey @vedant-jain03, you can checkout the PR.

**Comment by vedant-jain03** [comment]
@Shubham29012001 good work
But you have rewritten lines of codes in `Main.js` and as a result, it is showing unexpected added lines and deleted lines of code, kindly just add the implementation for this function and undo the code which is not being manupulated with this function.

Can you explain the reason why you added some extra node-modules in package-lock.json file?

**Comment by Shubham29012001** [comment]
Hey @vedant-jain03, since I am using the prettier extension. It automatically prettifies the codes we open. I have opened Main.js just to check the code and the prettier had just prettified the code and nothing else. For package-lock.json and package.json, I have used a package react-component-export-image.

**Comment by vedant-jain03** [comment]
> Hey @vedant-jain03, since I am using the prettier extension. It automatically prettifies the codes we open. I have opened Main.js just to check the code and the prettier had just prettified the code and nothing else. There is no code changes in main.js from my side and the website is working perfectly well. For package-lock.json and package.json, I have used a lightweight package react-component-export-image.

Hmm, I see
But I suggest you not to use auto file modification extension, not for at least open source as it may lead to unnecessary code line credit.
I got the thing about node modules now.
Good work 👍🏼

**Review by vedant-jain03 — APPROVED** [review]

**Comment by Shubham29012001** [comment]
Hey @vedant-jain03, yes I will now make sure that I don't use auto prettify on code. Thanks for your suggestion. Can you please look out at the other issue created by me regarding the tooltip too? I have already implemented it. Just need to create a separate PR for it.

**Pull request merged**
