### PR TITLE
Added yarn usage in readme

### PR DESCRIPTION
**Pull request by VaibhavUpreti**
githug
 
This is how the readme looks now. :)

Also added the yarn.lock file.

### CODE REVIEW

**Comment by VaibhavUpreti** [comment]
This contribution is made under GSSOC'22

**Review by vedant-jain03 — COMMENTED** [review]
Remove yarn.lock from commit

**Comment by VaibhavUpreti** [comment]
removed the file @vedant-jain03

**Review by vedant-jain03 — APPROVED** [review]

**Comment by vedant-jain03** [comment]
@DhairyaBahl review and merge.

**Pull request merged**
